{% set version = "1.23.0" %}

package:
  name: geocoder
  version: {{ version }}

source:
  fn: geocoder-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/geocoder/geocoder-{{ version }}.tar.gz
  sha256: 4bb3e8557877dcf69e8e108a44356228de9e7bf1f15cc0f875365e2dc9fd089b
  patches:
    - setup_py-utf8.patch  # [win and py3k]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True
  entry_points:
    - geocode=geocoder.cli:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests
    - ratelim
    - click
    - six

test:
  imports:
    - geocoder

about:
  home: https://github.com/DenisCarriere/geocoder
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Geocoder is a simple and consistent geocoding library.'

extra:
  recipe-maintainers:
    - ocefpaf
