{% set version = "1.23.2" %}

package:
  name: geocoder
  version: {{ version }}

source:
  fn: geocoder-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/geocoder/geocoder-{{ version }}.tar.gz
  sha256: 5e294b87dc26482dc97d1aeee765c8db20161418c16ec125ea2bef8fffca5f2f
  patches:
    - setup_py-utf8.patch  # [win and py3k]

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - ratelim
    - click
    - six

test:
  imports:
    - geocoder
  commands:
    - geocode --help

about:
  home: https://github.com/DenisCarriere/geocoder
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Geocoder is a simple and consistent geocoding library.'

extra:
  recipe-maintainers:
    - ocefpaf
