{% set version = "1.36.0" %}

package:
  name: geocoder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geocoder/geocoder-{{ version }}.tar.gz
  sha256: ad23d015bffbdf9de4e0c5cf404f22421a3449cc9fdabc6e4ebd447c5ab15dc7

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - geocode = geocoder.cli:cli

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests
    - ratelim
    - click
    - orderedset
    - six

test:
  imports:
    - geocoder
  commands:
    - geocode --help

about:
  home: https://github.com/DenisCarriere/geocoder
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Geocoder is a simple and consistent geocoding library.'

extra:
  recipe-maintainers:
    - ocefpaf
