{% set version = "1.28.0" %}

package:
  name: geocoder
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geocoder/geocoder-{{ version }}.tar.gz
  sha256: 9dcdf6b38146504f6f5800ff230d743188ceadcabe46414b77e08dd67a28da37
  patches:
    - setup_py-utf8.patch  # [win and py3k]

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - geocode=geocoder:cli

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests
    - ratelim
    - click
    - orderedset
    - six

test:
  imports:
    - geocoder
  commands:
    - geocode --help

about:
  home: https://github.com/DenisCarriere/geocoder
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Geocoder is a simple and consistent geocoding library.'

extra:
  recipe-maintainers:
    - ocefpaf
