travis:
  secure:
    BINSTAR_TOKEN: IjyIuvi6VkqZavrXunt1u+GamvLn584yYyY4lghY48PyYNWA0605oGqNsJR5KboOLGMF91hqYzmOBId4hNptZMK3i8xWYPMhJOA6OqwujG3VGLgirrpjNfrK+6piymTJqLAZyn3uVnEJRytAWgqe+FEZXogm6/PUde/GE3HKD8F/o5YzwxlMMnrfme358x2x/zmf8waVZ1Esre4oTt46fAd1s0hpM12hZFenZRlFlMs7TLsAkulnPzNsljzAfp72jcceeJcCv1rtnfnB/Pb9na9SOoNvEJQ1dQdwDwFQQxXS01qzEtj8fL4mbUVXvZYP4MDtMGyBV23xF/LbrLduQwsQ3T3dbmZ7ay6Ixm+pHvY1bRTZk4AO0NgXdPDR7mC/lXwnkc7ootUgLukEjAA2CYlgikj4DLdUO7kVPgwN55wVjagJSxrr6I+cT/yyzCPa8/wOJx+wnYbWnDauP8+goeFuAPLwDkzPeyMzHo4t4lzBn6Uk1xpGOqhxQezbsK0+TtzUM5dulucX/235V9mN92HmiSYkOI56WOFpi6idESNe5r420v9JPWXq1QXNRTZbu+Z2r0/Yh3qsHTM0s6a8e5KtJpaXAyM0CdYIe4hiIj2KHAMwLiBxKv7yLPRNBxm1U/n5xP/uT6MnVEErIixDMhI/0KmHklAUyppRtgPhu5A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
