travis:
  secure:
    BINSTAR_TOKEN: hINDFzwqJhFCPcPXe3iCnj9q68tH4vUJ3QEerGjaa6Yt10jU+0XBaqQRCKn5W4S3JtHktesIdHaDSRhRz7CbSizqQoWg2PZAst06L/5n0cVfGk4YW7w3fr9/KObBqj/fk8kn7kIbqHDsYg/qnhL1tVmessQRVdWx/GatuG9xa/sPe3rXDI1xczTSzsHs6ff6WGysadCJRhHJcHFn0TZSEMDj2UhguMzERX+TimIuNUeUMWCJ75/t1DfJqcwmefSxtdcJ2Q02+rB5kCTtJ/VgcgcMsyNmeUNOkBU+XbWlbnrgQXZYeGJ5Q7KcC0gw2EWQ9n3QX9KMX4YmkvkpB8AnQeyYb92oP7tjGW398ZTgrF4AF71nZne3l6y2vf7+rYBSpx7Kuehm8kbKlaABNy/I3a8gpbLJSl7PqvZfarTPRLXmr3vG9DOI1HvtZhIx70SedMec7DN5idYHyFbK/zq5j0HdNB4Hyc62tsz2tonN+wNQHhqAmJx9LUTMl2SD4e7+q/d3e9T9a45iPmVL/PKUCHh2RiWYCzKDXUnH+0DDDqyqJQBmXmsxaqnOkXpzXaUYlLZvkZY13mFiI1RCTsNAP9Y91EOoKFQOt+AzYIy1SPCZoFgjmVslIarV5JWmtplupdHd63CA+ICV0c+Pjcubtq98a7di8zPH5MBw3MCE+oE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
