travis:
  secure:
    BINSTAR_TOKEN: G4y6N1KqDBkwB/dMV60v99FAM07K4GC6rVhhxNacADXZt92bu56Cyv+dzu7eD7vqkRXxa1AnX5uT9dH7eDdCU+PISFRNXHeqbsph+R4n2jIW5Cd0R7q3jSseQBvXQfaIbV34osGpI3LlBs8D1g/Rfh45bkPvJLz3Ep/F98r0EdK+1muNHNbum+7JwhC1gD+rjEfWFNohwYu305vVSIyCE+CMEXQCdCfxIpK/DSunFi+fBDqfldKlw5sZku12j7L23ahgEcDkyIGMvXVVg0V80IwqrG9sJbXfZTUPuAPjwAg3HBUMGRHpF7rxoT78sfM3P61RjAVQ5obLghxWrtT8AJnXSU59JTlnOhYwKrvxv/4m38vStvduZ1KWbJCbWu3HKfal4JnwkcRB7OQ36EWNPpiuX5dzkuENg7kd5ypX67HhHdB4Uz9Xjze1Z1TXLrrl9azAYqT6YWDzDxp1jmd23GGMLR28rLLgnfdeO4N9wrNEogEjNRkx/H0pR+dfBfms9pCEt3KCatvWN9z11iPChggoepUa+3e2lHisKfcNvhlk7qKWulQwdmuFMGwq5CCnUNdqkzP7l8nTYmBiE4IwY5vkoWnJy/ZKWOd5F14Mzg2dUBwAoSr5tO3WTlx0ik+gp2ksEF6tLzj5EJLItX+tanfBbgNyDzEbasXhOnh7bfU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
